spring:
  application:
    name: mykytadu-api
  docker:
    compose:
      enabled: false
  flyway:
    sql-migration-separator: "-"
    validate-migration-naming: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,metrics
